routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TrainController;
use App\Http\Controllers\HomeController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::resource('admin/train', TrainController::class);
Route::match(['get', 'post'], 'train/{id}', [App\Http\Controllers\HomeController::class, 'single'])->name('home.single');
Route::post('booking/confirm', [App\Http\Controllers\HomeController::class, 'book'])->name('home.book');
Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Booking.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Booking extends Model
{

    use HasFactory;

}

app/Models/Train.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Train extends Model
{
    use HasFactory;

    public function getAvailableSeatAttribute()
    {
        $obj = Booking::select(DB::raw("SUM(seat_count) as seat_count"))->where('train_id', $this->id)->first();

        return ($this->seats - $obj->seat_count);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Booking;
use App\Models\Train;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {

    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $trains = Train::all();

        return view('home.index', compact('trains'));
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function single($id, Request $request)
    {
        if(isset($_POST) && !empty($_POST)) {
            $validatedData = $request->validate([
                'nic' => 'required|regex:/^\d{9}V$/',
                'seat_count' => 'required|integer'
            ]);

            $booking = new Booking();
            $booking->nic = $request->nic;
            $booking->seat_count = $request->seat_count;
            $booking->train_id = $request->train_id;

            $booking->save();

            return redirect('/')->with('success', 'Booking is completed Successfully. Your Booking ID : ' . $booking->id);
        } else {
            $train = Train::find($id);

            return view('home.single', compact('train'));
        }
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function book()
    {

    }
}

app/Http/Controllers/TrainController.php
<?php

namespace App\Http\Controllers;

use App\Models\Train;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

class TrainController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $trains = Train::all();

        return view('train.index', compact('trains'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('train.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'required',
            'departure_datetime' => 'required',
            'seats' => 'required|integer'
        ]);

        $train = new Train();
        $train->name = $request->name;
        $train->departure_datetime = $request->departure_datetime;
        $train->seats = $request->seats;

        $train->save();

        return redirect('admin/train')->with('success', 'Created Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $train = Train::find($id);

        return view('train.edit', compact('train'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([
            'name' => 'required',
            'departure_datetime' => 'required',
            'seats' => 'required|integer'
        ]);

        $train = Train::find($id);
        $train->name = $request->name;
        $train->departure_datetime = $request->departure_datetime;
        $train->seats = $request->seats;

        $train->save();

        return redirect('admin/train')->with('success', 'Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home/index.blade.php
@extends('layouts/app')

@section('content')
<div class="row">
    <div class="col-md-12">
        <h2>Find Your Traveling Journey</h2>
    </div>
</div>

@include('partials/msg')

<div class="table-responsive mt-3">
    <table class="table table-striped table-sm">
        <thead>
        <tr>
            <th>#</th>
            <th>Train Name</th>
            <th>Departure Date & Time</th>
            <th>Total Seats</th>
            <th>Available Seats</th>
            <th>****</th>
        </tr>
        </thead>
        <tbody>
        @foreach($trains as $train)
            <tr>
                <td>{{ $train->id }}</td>
                <td>{{ $train->name }}</td>
                <td>{{ $train->departure_datetime }}</td>
                <td>{{ $train->seats }}</td>
                <td  class="text-success">{{ $train->available_seat }}</td>
                <td>
                    @if($train->available_seat <= 0)
                        <span class="text-danger">All seats are booked...</span>
                    @elseif (strtotime($train->departure_datetime) <= now()->timestamp)
                        <span class="text-danger">Departure Date is passed...</span>
                    @else
                        <a type="button" class="btn btn-outline-dark" href="{{ route('home.single', [$train->id]) }}">Book</a>
                    @endif
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>
@endsection

resources/views/home/single.blade.php
@extends('layouts/app')

@section('content')
<div class="row">
    <div class="col-md-12">
        <h2>Book Train - [{{ $train->name }}]</h2>
    </div>
</div>

@include('partials/msg')

<div class="table-responsive mt-3 single">
    <div class="card">
        <table class="table table-striped table-sm mb-2">
            <tbody>
                <tr>
                    <td><strong>Train Name</strong></td>
                    <td>{{ $train->name }}</td>
                </tr>
                <tr>
                    <td><strong>Departure Date & Time</strong></td>
                    <td>{{ $train->departure_datetime }}</td>
                </tr>
                <tr>
                    <td><strong>Total Seats</strong></td>
                    <td>{{ $train->seats }}</td>
                </tr>
                <tr>
                    <td><strong>Available Seats</strong></td>
                    <td class="text-success">{{ $train->available_seat }}</td>
                </tr>
            </tbody>
        </table>
        <form method="post" action="{{route('home.single', [$train->id])}}">
            <div class="card-body">
                @csrf
                <div class="form-group">
                    <label for="name">NIC</label>
                    <input type="text" id="nic" name="nic" class="form-control">
                    <input type="hidden" id="train_id" name="train_id" value="{{ $train->id }}">
                </div>
                <div class="form-group">
                    <label for="seats">Seat Count</label>
                    <input type="number" id="seat_count" name="seat_count" class="form-control">
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Book and Confirm</button>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <!-- Custom styles for this template -->

</head>
<body>
<nav class="navbar navbar-dark bg-dark flex-md-nowrap px-3 shadow">
    <div class="container">
        <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Train Booking System</a>

        <ul class="navbar-nav" style="flex-direction: row;">
            <!-- Authentication Links -->
            @guest
                @if (Route::has('login'))
                    <li class="nav-item px-2">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>
                @endif

                @if (Route::has('register'))
                    <li class="nav-item px-2">
                        <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                    </li>
                @endif
            @else
                <li class="nav-item px-2">
                    <a class="nav-link" href="{{ route("home") }}">Book</a>
                </li>
                <li class="nav-item px-2 mr-5">
                    <a class="nav-link" href="{{ route("train.index") }}">Trains</a>
                </li>
                <li class="nav-item dropdown">
                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ Auth::user()->name }}
                    </a>

                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                            @csrf
                        </form>
                    </div>
                </li>
            @endguest
        </ul>
    </div>
</nav>
<div class="container">
    <div class="row">
        <main role="main" class="col-md-12 ml-sm-auto px-4">
            @yield('content')
        </main>
    </div>
</div>
</html>

resources/views/partials/msg.blade.php
@if(Session::has('success'))
    <div class="alert alert-success">
        {{ Session::get('success') }}
        @php
            Session::forget('success');
        @endphp
    </div>
@endif
@if (count($errors) > 0)
    <div class="alert alert-danger">
        @foreach($errors->all() as $error)
            {{ $error }} <br>
        @endforeach
    </div>
@endif

resources/views/partials/sidebar.blade.php
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
    <div class="sidebar-sticky">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link active" href="#">
                    <span data-feather="home"></span>
                    Dashboard <span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="file"></span>
                    Orders
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="shopping-cart"></span>
                    Products
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="users"></span>
                    Customers
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="bar-chart-2"></span>
                    Reports
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="layers"></span>
                    Integrations
                </a>
            </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>Saved reports</span>
            <a class="d-flex align-items-center text-muted" href="#" aria-label="Add a new report">
                <span data-feather="plus-circle"></span>
            </a>
        </h6>
        <ul class="nav flex-column mb-2">
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="file-text"></span>
                    Current month
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="file-text"></span>
                    Last quarter
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="file-text"></span>
                    Social engagement
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="file-text"></span>
                    Year-end sale
                </a>
            </li>
        </ul>
    </div>
</nav>

resources/views/train/create.blade.php
@extends('layouts/app')

@section('content')
<div class="row">
    <div class="col-md-12">
        <h2>Create New Train</h2>
    </div>
</div>

@include('partials/msg')

<div class="table-responsive mt-3">
    <div class="card">
        <form method="post" action="{{route('train.store')}}">
            <div class="card-body">
                @csrf
                <div class="form-group">
                    <label for="name">Train Name</label>
                    <input type="text" id="name" name="name" class="form-control">
                </div>
                <div class="form-group">
                    <label for="departure_datetime">Departure Date & Time</label>
                    <input type="datetime-local" id="departure_datetime" name="departure_datetime" class="form-control">
                </div>
                <div class="form-group">
                    <label for="seats">Departure Date & Time</label>
                    <input type="number" id="seats" name="seats" class="form-control">
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Create</button>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/train/edit.blade.php
@extends('layouts/app')

@section('content')
<div class="row">
    <div class="col-md-12">
        <h2>Edit Train - [{{ $train->name }}]</h2>
    </div>
</div>

@include('partials/msg')

<div class="table-responsive mt-3">
    <div class="card">
        <form method="post" action="{{route('train.update', [$train->id])}}">
            <div class="card-body">
                @csrf
                @method('PATCH')
                <div class="form-group">
                    <label for="name">Train Name</label>
                    <input type="text" id="name" name="name" class="form-control" value="{{$train->name}}">
                </div>
                <div class="form-group">
                    <label for="departure_datetime">Departure Date & Time</label>
                    <input type="datetime-local" id="departure_datetime" name="departure_datetime" class="form-control"  value="{{date('Y-m-d\TH:i', strtotime($train->departure_datetime))}}">
                </div>
                <div class="form-group">
                    <label for="seats">Departure Date & Time</label>
                    <input type="number" id="seats" name="seats" class="form-control" value="{{$train->seats}}">
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Edit</button>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/train/index.blade.php
@extends('layouts/app')

@section('content')
<div class="row">
    <div class="col-md-10">
        <h2>All Trains</h2>
    </div>
    <div class="col-md-2">
        <a type="button" class="btn btn-info" href="{{ route('train.create') }}">Create New Train</a>
    </div>
</div>

@include('partials/msg')

<div class="table-responsive mt-3">
    <table class="table table-striped table-sm">
        <thead>
        <tr>
            <th>#</th>
            <th>Train Name</th>
            <th>Departure Date & Time</th>
            <th>Available Seats</th>
            <th>Operation</th>
        </tr>
        </thead>
        <tbody>
        @foreach($trains as $train)
            <tr>
                <td>{{ $train->id }}</td>
                <td>{{ $train->name }}</td>
                <td>{{ $train->departure_datetime }}</td>
                <td>{{ $train->seats }}</td>
                <td>
                    <a type="button" class="btn btn-warning btn-sm" href="{{ route('train.edit', [$train->id]) }}">Edit</a>
                    <a type="button" class="btn btn-danger btn-sm ml-1" href="#">Delete</a>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>
@endsection